config/routes.rb
Rails.application.routes.draw do
resources :pro_heals
    root 'pro_heals#index'

end

app/models/pro_heal.rb
class ProHeal < ActiveRecord::Base
  validates_format_of :phone, :with =>  /\A0[0-9]{9}\Z/, :on => :create
  mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pro_heals_controller.rb
class ProHealsController < ApplicationController
    def index
        @pro_heal = ProHeal.all
    end

    def new
        @pro_heal = ProHeal.new
    end

    def create
        pro_heal = ProHeal.new(params_pro_heal)
        pro_heal.avatar = params[:file]
        pro_heal.save
        redirect_to root_path
    end

    def show
        @pro_heal = ProHeal.find(params[:id])
    end

    def destroy
      pro_heal = ProHeal.find(params[:id])
      pro_heal.delete
      redirect_to root_path
    end

    private

    def params_pro_heal
        params.require(:pro_heal).permit(:name, :surname, :phone, :location, :job, :city, :postal_code, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pro_heals_helper.rb
module ProHealsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShopmycoursesTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse" style="background-color: #333333!important" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">ShopMyCourses-Test</a>
    </div>
    <div class="collapse navbar-collapse" id="navbar">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Liste des pros',root_path, method: :get %></li>
        <li><%= link_to 'Ajouter un Pro', new_pro_heal_path, method: :get %></li>

      </ul>
    </div>
  </div>
</nav>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/pro_heals/index.html.erb
<table class="table table-striped table-condensed">
    <tr>
        <th>
            Name
        </th>
        <th>
            Firstname
        </th>
        <th>
            City
        </th>
        <th>
            Job
        </th>
        <th>
            <span class="glyphicon glyphicon-eye-open"></span>
            More
        </th>
    </tr>
    <% @pro_heal.each do |p| %>
    <tr>
        <td>
            <%=p.name %>
        </td>
        <td>
            <%=p.surname %>
        </td>
        <td>
            <%= p.city %>
        </td>
        <td>
            <%= p.job %>
        </td>
        <td>
            <%= button_to 'More', pro_heal_path(p.id), method: :get, class: 'btn btn-danger' %><br/><br/>
        </td>
    </tr>
    <% end %>
</table>
<br/>

app/views/pro_heals/new.html.erb
<div class="row">
    <div class="col-md-8 col-md-offset-2">

        <%= form_for @pro_heal do |f| %>
        <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
            <%= f.label :Firstname %>
            <%= f.text_field :surname, class: 'form-control' %>
        </div>
        <div class="form-group">
            <%= f.label :phone %>
            <%= f.text_field :phone, class: 'form-control' %>
        </div>
        <div class="form-group">
            <%= f.label :location %>
            <%= f.text_field :location, class: 'form-control' %>
        </div>
        <div class="form-group">
            <%= f.label :postal_code %>
            <%= f.text_field :postal_code, class: 'form-control' %>
        </div>
        <div class="form-group">
            <%= f.label :city %>
            <%= f.text_field :city, class: 'form-control' %>
        </div>
        <div class="form-group">
            <%= f.label :job %>
            <%= f.text_field :job, class: 'form-control' %>
        </div>
        <div class="form-group">
            <%= f.label :avatar %>
            <%= f.file_field :avatar, class: 'form-control' %>
        </div>

        <%= f.submit 'Save', :class => 'btn btn-primary btn-block' %>
        <% end %>
    </div>
</div>

app/views/pro_heals/show.html.erb
<div class="row">
    <div class="col-md-4 text-right">
      <%=@pro_heal.name %><br/>
      <%=@pro_heal.surname %><br/>
      <a href="tel:<%=@pro_heal.phone %>"><%=@pro_heal.phone %></a><br/>
      <%=@pro_heal.location %><br/>
      <%= @pro_heal.job %><br/>
      <%= @pro_heal.city %><br/>
      <%= @pro_heal.postal_code %><br/>
      <img src="<%= @pro_heal.avatar %>", style="max-width: 70%"/><br/><br/>
      <%= button_to "Delete", pro_heal_path(@pro_heal.id), method: :delete, class: 'btn btn-danger' %>
    </div>
    <div class="col-md-8">
        <div id="map" style='width: 100%; height: 400px;'></div>
    </div>
    <script>
        var map;
        function load() {
            var geocoding = new google.maps.Geocoder();
            var address = "<%= @pro_heal.location + " " + @pro_heal.postal_code + " " + @pro_heal.city %>";
            geocoding.geocode({
                'address': address
            }, function (results, status) {
                if (status == google.maps.GeocoderStatus.OK) {
                    var latLng = {
                        lat: results[0].geometry.location.lat(),
                        lng: results[0].geometry.location.lng()
                    };
                    map = new google.maps.Map(document.getElementById('map'), {
                        center: latLng,
                        zoom: 16
                    });
                    var marker = new google.maps.Marker({position: latLng, map: map});
                }
            });
        }
    </script>

    <script src="//maps.google.com/maps/api/js?v=3.23&key=AIzaSyDAI14Tu4cnD7fGM7bSqAMtxwee4J3TC_U&callback=load"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
</div>